// Generated by src/build_toolkit.py - do not edit by hand.
// VERSION is a hash of the built page, so each data refresh publishes a new
// cache and clients stop serving stale numbers.
var CACHE = "qs-toolkit-e5954516d370";
var PRECACHE = [
  "./",
  "manifest.webmanifest",
  "assets/fonts.css",
  "assets/fonts/cinzel-600.woff2",
  "assets/fonts/cinzel-700.woff2",
  "assets/fonts/ibm-plex-mono-400.woff2",
  "assets/fonts/ibm-plex-mono-500.woff2",
  "assets/fonts/ibm-plex-mono-600.woff2",
  "assets/fonts/ibm-plex-sans-400.woff2",
  "assets/fonts/ibm-plex-sans-500.woff2",
  "assets/fonts/ibm-plex-sans-600.woff2",
  "assets/apple-touch-icon.png",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512.png"
];

self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    // One bad asset must not fail the whole install.
    return Promise.all(PRECACHE.map(function (u) {
      return c.add(new Request(u, { cache: "reload" }))["catch"](function () {});
    }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) {
      return k === CACHE ? null : caches.delete(k);
    }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== location.origin) return;

  // Navigations: network first, so a refresh lands as soon as there is
  // signal; fall back to cache so the app still opens with no connection.
  if (req.mode === "navigate") {
    e.respondWith(fetch(req).then(function (res) {
      var copy = res.clone();
      caches.open(CACHE).then(function (c) { c.put("./", copy); });
      return res;
    })["catch"](function () {
      return caches.match("./").then(function (r) {
        return r || caches.match("index.html");
      });
    }));
    return;
  }

  // Fonts, icons, manifest: immutable within a version, so cache first.
  e.respondWith(caches.match(req).then(function (hit) {
    return hit || fetch(req).then(function (res) {
      if (res && res.ok && res.type === "basic") {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put(req, copy); });
      }
      return res;
    });
  }));
});
